import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "./_components/sidebar";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Stockly",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"], display: "auto" });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen antialiased`}>
        <div className="flex h-full">
          <Sidebar />
          <div className="min-h-screen w-full bg-gray-100 px-8 py-6">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
